/**
 * Labels des champs Google Merchant Center pour l'affichage catalogue / fiche produit.
 */
export function getFieldLabel(fieldKey: string): string {
  const labels: Record<string, string> = {
    id: 'ID produit',
    title: 'Titre',
    description: 'Description',
    link: 'URL produit',
    image_link: 'Image principale',
    additional_image_link: 'Images supplémentaires',
    mobile_link: 'URL mobile',
    price: 'Prix',
    sale_price: 'Prix promotionnel',
    sale_price_effective_date: 'Dates promotion',
    availability: 'Disponibilité',
    availability_date: 'Date disponibilité',
    cost_of_goods_sold: 'Coût des marchandises',
    expiration_date: "Date d'expiration",
    google_product_category: 'Catégorie Google',
    product_type: 'Type de produit',
    brand: 'Marque',
    gtin: 'GTIN / Code-barres',
    mpn: 'MPN / Numéro fabricant',
    identifier_exists: 'Identifiant existe',
    condition: 'Condition',
    color: 'Couleur',
    size: 'Taille',
    material: 'Matériau',
    pattern: 'Motif',
    gender: 'Genre',
    age_group: "Groupe d'âge",
    size_type: 'Type de taille',
    size_system: 'Système de taille',
    item_group_id: 'ID de groupe',
    multipack: 'Multipack',
    is_bundle: 'Est un bundle',
    adult: 'Adulte',
    energy_efficiency_class: 'Classe efficacité énergétique',
    min_energy_efficiency_class: 'Classe min efficacité',
    max_energy_efficiency_class: 'Classe max efficacité',
    quantity: 'Quantité',
    shipping: 'Expédition',
    shipping_label: 'Label expédition',
    shipping_weight: 'Poids expédition',
    shipping_length: 'Longueur expédition',
    shipping_width: 'Largeur expédition',
    shipping_height: 'Hauteur expédition',
    max_handling_time: 'Temps traitement max',
    min_handling_time: 'Temps traitement min',
    transit_time_label: 'Label temps transit',
    pickup_method: 'Méthode retrait',
    pickup_SLA: 'SLA retrait',
    unit_pricing_measure: 'Mesure prix unitaire',
    unit_pricing_base_measure: 'Base prix unitaire',
    tax: 'Taxe',
    tax_category: 'Catégorie taxe',
    promotion_id: 'ID promotion',
    excluded_destination: 'Destination exclue',
    included_destination: 'Destination incluse',
    loyalty_program: 'Programme de fidélité',
    loyalty_program_program_label: 'Label programme',
    loyalty_program_tier_label: 'Label niveau',
    loyalty_program_price: 'Prix membre',
    loyalty_program_loyalty_points: 'Points de fidélité',
    loyalty_program_member_price_effective_date: 'Dates effet prix membre',
    loyalty_program_shipping_label: 'Label expédition membre',
    loyalty_program_cashback_for_future_use: 'Cashback',
    custom_label_0: 'Label personnalisé 0',
    custom_label_1: 'Label personnalisé 1',
    custom_label_2: 'Label personnalisé 2',
    custom_label_3: 'Label personnalisé 3',
    custom_label_4: 'Label personnalisé 4',
    asin: 'ASIN',
    isbn: 'ISBN',
    upc: 'UPC',
    ean: 'EAN',
    bullet_point_1: 'Bullet point 1',
    bullet_point_2: 'Bullet point 2',
    bullet_point_3: 'Bullet point 3',
    bullet_point_4: 'Bullet point 4',
    bullet_point_5: 'Bullet point 5',
    product_tax_code: 'Code taxe produit',
    sku: 'SKU / Référence',
    url: 'URL produit',
    imageUrl: 'Image',
    inventory: 'Stock',
    currency: 'Devise',
  };
  return labels[fieldKey] || fieldKey;
}

export function getAvailableFields(): { key: string; label: string }[] {
  return [
    { key: 'id', label: 'ID produit' },
    { key: 'title', label: 'Titre' },
    { key: 'description', label: 'Description' },
    { key: 'link', label: 'URL produit' },
    { key: 'image_link', label: 'Image principale' },
    { key: 'additional_image_link', label: 'Images supplémentaires' },
    { key: 'mobile_link', label: 'URL mobile' },
    { key: 'price', label: 'Prix' },
    { key: 'sale_price', label: 'Prix promotionnel' },
    { key: 'sale_price_effective_date', label: 'Dates promotion' },
    { key: 'availability', label: 'Disponibilité' },
    { key: 'availability_date', label: 'Date disponibilité' },
    { key: 'cost_of_goods_sold', label: 'Coût des marchandises' },
    { key: 'expiration_date', label: "Date d'expiration" },
    { key: 'google_product_category', label: 'Catégorie Google' },
    { key: 'product_type', label: 'Type de produit' },
    { key: 'brand', label: 'Marque' },
    { key: 'gtin', label: 'GTIN / Code-barres' },
    { key: 'mpn', label: 'MPN / Numéro fabricant' },
    { key: 'identifier_exists', label: 'Identifiant existe' },
    { key: 'condition', label: 'Condition' },
    { key: 'color', label: 'Couleur' },
    { key: 'size', label: 'Taille' },
    { key: 'material', label: 'Matériau' },
    { key: 'pattern', label: 'Motif' },
    { key: 'gender', label: 'Genre' },
    { key: 'age_group', label: "Groupe d'âge" },
    { key: 'size_type', label: 'Type de taille' },
    { key: 'size_system', label: 'Système de taille' },
    { key: 'item_group_id', label: 'ID de groupe' },
    { key: 'multipack', label: 'Multipack' },
    { key: 'is_bundle', label: 'Est un bundle' },
    { key: 'adult', label: 'Adulte' },
    { key: 'energy_efficiency_class', label: 'Classe efficacité énergétique' },
    { key: 'min_energy_efficiency_class', label: 'Classe min efficacité' },
    { key: 'max_energy_efficiency_class', label: 'Classe max efficacité' },
    { key: 'quantity', label: 'Quantité' },
    { key: 'shipping', label: 'Expédition' },
    { key: 'shipping_label', label: 'Label expédition' },
    { key: 'shipping_weight', label: 'Poids expédition' },
    { key: 'shipping_length', label: 'Longueur expédition' },
    { key: 'shipping_width', label: 'Largeur expédition' },
    { key: 'shipping_height', label: 'Hauteur expédition' },
    { key: 'max_handling_time', label: 'Temps traitement max' },
    { key: 'min_handling_time', label: 'Temps traitement min' },
    { key: 'transit_time_label', label: 'Label temps transit' },
    { key: 'pickup_method', label: 'Méthode retrait' },
    { key: 'pickup_SLA', label: 'SLA retrait' },
    { key: 'unit_pricing_measure', label: 'Mesure prix unitaire' },
    { key: 'unit_pricing_base_measure', label: 'Base prix unitaire' },
    { key: 'tax', label: 'Taxe' },
    { key: 'tax_category', label: 'Catégorie taxe' },
    { key: 'promotion_id', label: 'ID promotion' },
    { key: 'excluded_destination', label: 'Destination exclue' },
    { key: 'included_destination', label: 'Destination incluse' },
    { key: 'loyalty_program', label: 'Programme de fidélité' },
    { key: 'loyalty_program_program_label', label: 'Label programme' },
    { key: 'loyalty_program_tier_label', label: 'Label niveau' },
    { key: 'loyalty_program_price', label: 'Prix membre' },
    { key: 'loyalty_program_loyalty_points', label: 'Points de fidélité' },
    { key: 'loyalty_program_member_price_effective_date', label: 'Dates effet prix membre' },
    { key: 'loyalty_program_shipping_label', label: 'Label expédition membre' },
    { key: 'loyalty_program_cashback_for_future_use', label: 'Cashback' },
    { key: 'custom_label_0', label: 'Label personnalisé 0' },
    { key: 'custom_label_1', label: 'Label personnalisé 1' },
    { key: 'custom_label_2', label: 'Label personnalisé 2' },
    { key: 'custom_label_3', label: 'Label personnalisé 3' },
    { key: 'custom_label_4', label: 'Label personnalisé 4' },
    { key: 'asin', label: 'ASIN' },
    { key: 'isbn', label: 'ISBN' },
    { key: 'upc', label: 'UPC' },
    { key: 'ean', label: 'EAN' },
    { key: 'bullet_point_1', label: 'Bullet point 1' },
    { key: 'bullet_point_2', label: 'Bullet point 2' },
    { key: 'bullet_point_3', label: 'Bullet point 3' },
    { key: 'bullet_point_4', label: 'Bullet point 4' },
    { key: 'bullet_point_5', label: 'Bullet point 5' },
    { key: 'product_tax_code', label: 'Code taxe produit' },
  ];
}
